title: Sokol-Hessner Lab Onboarding
description: Get set up with the Sokol-Hessner Lab!
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
logo: ./files/lab_logo.png